Other pet
KevinLewisIowa/JoppaTest pull request #41
Opened 2020-09-29 02:07 UTC by addelian

2020-10-01 01:15 UTC, wilsont3 requested changes
@addelian This is really close.  I have written notes on a couple of lines for you to review.  Please let me know if you have any questions.

2020-10-01 01:15 UTC, wilsont3 commented on src/app/models/client-pet.ts
> +    species: string = undefined;
Since we are no longer using this, go ahead and remove it.

2020-10-01 01:15 UTC, wilsont3 commented on src/app/insert-modals/pets/pets.component.ts
> +      if (this.extraInfoNeeded && (pet.pet_type === '' || pet.pet_type === null)) {
Does it make sense for this check be up (line 50) when know that extraInfoNeeded and to be a check to see if extraInfo is empty string or null?

2020-10-08 22:18 UTC, addelian commented on src/app/models/client-pet.ts
> +    species: string = undefined;
Done! Haven't pushed up the changes yet because I have a question on the other comment.

2020-10-08 22:18 UTC, addelian commented on src/app/insert-modals/pets/pets.component.ts
> +      if (this.extraInfoNeeded && (pet.pet_type === '' || pet.pet_type === null)) {
Hey @wilsont3, I'm not fully tracking on this one. The way I have it now is an alert if the user submits and the field is empty. Are you suggesting that I rebuild it up by 50 so that the user gets the alert as soon as they choose Other pet instead of dog or cat?

2020-10-08 22:20 UTC, addelian commented on src/app/insert-modals/pets/pets.component.ts
> +      if (this.extraInfoNeeded && (pet.pet_type === '' || pet.pet_type === null)) {
`if (this.extraInfoNeeded && (this.extraInfo === '' || this.extraInfo === null)){ 
          alert('Need to enter species of pet');
        }`

That's where I'm at right now from 50-52 in my spitballing but it's not working as-is.

2020-10-09 01:37 UTC, wilsont3 commented on src/app/insert-modals/pets/pets.component.ts
> +      if (this.extraInfoNeeded && (pet.pet_type === '' || pet.pet_type === null)) {
@addelian I see what you are doing to check if the pet_type is an empty string (ie the user did not enter an Other Pet).  Right after this, though, regardless of the alert, you are still always inserting the pet.  I would imagine that meant to put a `else {}` are the insertpet function.

2020-10-28 00:46 UTC, wilsont3 requested changes

2020-10-28 00:46 UTC, wilsont3 commented on src/app/insert-modals/pets/pets.component.ts
> +      if (this.extraInfoNeeded && (this.extraInfo === '' || this.extraInfo === null)){
This is still so close.  I noticed that there is not a way to handle if one of the original pet types (not other) is chosen.  This is because there is still the case of pet_type not being null and extraInfoNeeded = false.  I think after this is resolved, it should work.

2020-11-09 22:26 UTC, addelian commented
@wilsont3 I'm not sure how the situation you're describing is different than my catch-all "else" that I originally wrote, but I specified it as an else if after my original conditional, and then still put the same else logic afterwards. Thanks for your input!

2020-11-12 01:29 UTC, wilsont3 approved these changes

2020-11-12 03:38 UTC, merged