added back button; found a bug
KevinLewisIowa/JoppaTest pull request #48
Opened 2021-03-12 00:55 UTC by john-william-cross

2021-03-12 04:31 UTC, wilsont3 requested changes
Great job on getting this ready to both of you!  Simply by making this one change, I think that this should be ready to go.

2021-03-12 04:31 UTC, wilsont3 commented on src/app/admin-client-inactive-updater/admin-client-inactive-updater.component.html
> +      (click)="back()"
This throws an error since there is no "back()" method in the typescript.  If I remember correctly, the routerLink attribute makes this so that it is not needed.

2021-03-12 14:47 UTC, john-william-cross commented
I will take a look. Where/when was the error? I wasn’t seeing one; back
button worked for me.

On Thu, Mar 11, 2021 at 8:31 PM wilsont3 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Great job on getting this ready to both of you! Simply by making this one
> change, I think that this should be ready to go.
> ------------------------------
>
> In
> src/app/admin-client-inactive-updater/admin-client-inactive-updater.component.html
> <https://github.com/KevinLewisIowa/JoppaTest/pull/48#discussion_r592902698>
> :
>
> > -    <p *ngIf="countInactivated>0"> Number of Clients Inactivated: {{countInactivated}}</p>
> +    <div class="col-md-12 col-lg-12">
> +      <button class="btn btn-primary mt-3 mb-3" (click)="updateInactive()">
> +        Run Updater
> +      </button>
> +      <p *ngIf="countInactivated > 0">
> +        Number of Clients Inactivated: {{ countInactivated }}
> +      </p>
> +    </div>
> +  </div>
> +  <div class="card-footer">
> +    <button
> +      routerLink="/adminHome"
> +      class="btn btn-primary"
> +      style="float: left"
> +      (click)="back()"
>
> This throws an error since there is no "back()" method in the typescript.
> If I remember correctly, the routerLink attribute makes this so that it is
> not needed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KevinLewisIowa/JoppaTest/pull/48#pullrequestreview-610442217>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK7K2ATL3Y4QBRWL5QFVDHLTDGDJXANCNFSM4ZBJ7L6A>
> .
>

2021-03-13 14:41 UTC, wilsont3 commented
It was in the console

On Fri, Mar 12, 2021, 8:47 AM John Cross ***@***.***> wrote:

> I will take a look. Where/when was the error? I wasn’t seeing one; back
> button worked for me.
>
> On Thu, Mar 11, 2021 at 8:31 PM wilsont3 ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > Great job on getting this ready to both of you! Simply by making this one
> > change, I think that this should be ready to go.
> > ------------------------------
> >
> > In
> >
> src/app/admin-client-inactive-updater/admin-client-inactive-updater.component.html
> > <
> https://github.com/KevinLewisIowa/JoppaTest/pull/48#discussion_r592902698>
> > :
> >
> > > - <p *ngIf="countInactivated>0"> Number of Clients Inactivated:
> {{countInactivated}}</p>
> > + <div class="col-md-12 col-lg-12">
> > + <button class="btn btn-primary mt-3 mb-3" (click)="updateInactive()">
> > + Run Updater
> > + </button>
> > + <p *ngIf="countInactivated > 0">
> > + Number of Clients Inactivated: {{ countInactivated }}
> > + </p>
> > + </div>
> > + </div>
> > + <div class="card-footer">
> > + <button
> > + routerLink="/adminHome"
> > + class="btn btn-primary"
> > + style="float: left"
> > + (click)="back()"
> >
> > This throws an error since there is no "back()" method in the typescript.
> > If I remember correctly, the routerLink attribute makes this so that it
> is
> > not needed.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/KevinLewisIowa/JoppaTest/pull/48#pullrequestreview-610442217
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AK7K2ATL3Y4QBRWL5QFVDHLTDGDJXANCNFSM4ZBJ7L6A
> >
> > .
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/KevinLewisIowa/JoppaTest/pull/48#issuecomment-797535536>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIEF52JSE7BMNHH3S6LTZLTDISRDANCNFSM4ZBJ7L6A>
> .
>

2021-03-13 15:21 UTC, john-william-cross commented
I will take a look today or tomorrow, thanks!

On Sat, Mar 13, 2021 at 6:42 AM wilsont3 ***@***.***> wrote:

> It was in the console
>
> On Fri, Mar 12, 2021, 8:47 AM John Cross ***@***.***> wrote:
>
> > I will take a look. Where/when was the error? I wasn’t seeing one; back
> > button worked for me.
> >
> > On Thu, Mar 11, 2021 at 8:31 PM wilsont3 ***@***.***> wrote:
> >
> > > ***@***.**** requested changes on this pull request.
> > >
> > > Great job on getting this ready to both of you! Simply by making this
> one
> > > change, I think that this should be ready to go.
> > > ------------------------------
> > >
> > > In
> > >
> >
> src/app/admin-client-inactive-updater/admin-client-inactive-updater.component.html
> > > <
> >
> https://github.com/KevinLewisIowa/JoppaTest/pull/48#discussion_r592902698>
> > > :
> > >
> > > > - <p *ngIf="countInactivated>0"> Number of Clients Inactivated:
> > {{countInactivated}}</p>
> > > + <div class="col-md-12 col-lg-12">
> > > + <button class="btn btn-primary mt-3 mb-3" (click)="updateInactive()">
> > > + Run Updater
> > > + </button>
> > > + <p *ngIf="countInactivated > 0">
> > > + Number of Clients Inactivated: {{ countInactivated }}
> > > + </p>
> > > + </div>
> > > + </div>
> > > + <div class="card-footer">
> > > + <button
> > > + routerLink="/adminHome"
> > > + class="btn btn-primary"
> > > + style="float: left"
> > > + (click)="back()"
> > >
> > > This throws an error since there is no "back()" method in the
> typescript.
> > > If I remember correctly, the routerLink attribute makes this so that it
> > is
> > > not needed.
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/KevinLewisIowa/JoppaTest/pull/48#pullrequestreview-610442217
> > >,
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AK7K2ATL3Y4QBRWL5QFVDHLTDGDJXANCNFSM4ZBJ7L6A
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because your review was requested.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/KevinLewisIowa/JoppaTest/pull/48#issuecomment-797535536
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AJIEF52JSE7BMNHH3S6LTZLTDISRDANCNFSM4ZBJ7L6A
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KevinLewisIowa/JoppaTest/pull/48#issuecomment-798461423>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK7K2AQQ65LMOEBFKKUOWULTDN2UHANCNFSM4ZBJ7L6A>
> .
>

2021-03-15 21:49 UTC, merged

2021-03-15 21:52 UTC, john-william-cross commented
@wilsont3 @ebethluong I think I made the necessary changes and merged the request; can you double-check that it looks good though? Also, Elizabeth and I didn't know if these errors were an issue: 
<img width="1194" alt="Screen Shot 2021-03-15 at 2 42 54 PM" src="https://user-images.githubusercontent.com/46050562/111226279-1b0b8980-859e-11eb-8953-401049b72ccb.png">

2021-03-15 22:24 UTC, wilsont3 commented
Thanks! It looks good and you don't have to worry about those errors as
that is on the data side.

Tim

On Mon, Mar 15, 2021, 4:53 PM John Cross ***@***.***> wrote:

> @wilsont3 <https://github.com/wilsont3> @ebethluong
> <https://github.com/ebethluong> I think I made the necessary changes and
> merged the request; can you double-check that it looks good though? Also,
> Elizabeth and I didn't know if these errors were an issue:
> [image: Screen Shot 2021-03-15 at 2 42 54 PM]
> <https://user-images.githubusercontent.com/46050562/111226279-1b0b8980-859e-11eb-8953-401049b72ccb.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KevinLewisIowa/JoppaTest/pull/48#issuecomment-799779521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIEF56ME2CNAUL5T4YLY5TTDZ6UJANCNFSM4ZBJ7L6A>
> .
>