added remove button for tents for admins only
KevinLewisIowa/JoppaTest pull request #65
Opened 2022-03-25 01:19 UTC by addelian

2022-03-25 01:26 UTC, addelian commented
@wilsont3 My formatter got a hold of these files again :) the spots I changed were 510-562 in the .html, and around 710-719 in the .ts.

2022-03-25 03:01 UTC, wilsont3 requested changes
This looks very good, just the one change

2022-03-25 03:01 UTC, wilsont3 commented on src/app/client/servicing-client/servicing-client.component.html
> +              <td *ngIf="isAdmin">
@addelian This is potentially nit-picky, but could you put the *ngIf on the button.  I figure this will not make much of a difference, but then we would still have the column if not admin, we just would not have the button.

2022-03-25 20:54 UTC, addelian commented
@wilsont3 Awesome, I wasn't sure if ngIf worked on components like buttons. Thanks for explaining! I moved it, should be good to go.

2022-03-27 16:23 UTC, wilsont3 approved these changes
@addelian This looks good.  Go ahead and merge it in and I will get it reviewed by the Joppa staff

2022-03-28 18:06 UTC, merged