Feature/dwelling history UI
KevinLewisIowa/JoppaTest pull request #77
Opened 2022-11-22 02:42 UTC by addelian

@wilsont3 Everything is working as expected. Only question would be if we have the green light on moving the "First Time Homeless?" section as I haven't seen an answer from Megan yet. I went ahead and moved it, but I can roll back those changes if we want to keep those in place. I also removed the "Due to Covid" portion since it wasn't a part of the new requirements, but didn't make sense living in the details screen by itself. Happy to add that back into the dwelling portion if we're still looking to track that as well. Thanks for taking a look!

2022-11-22 03:39 UTC, wilsont3 commented
@addelian I will check on this tomorrow.  Thank you for your work on this.

On Mon, Nov 21, 2022 at 8:42 PM Nic Addelia ***@***.***>
wrote:

> @addelian <https://github.com/addelian> requested your review on: #77
> <https://github.com/KevinLewisIowa/JoppaTest/pull/77> Feature/dwelling
> history UI.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KevinLewisIowa/JoppaTest/pull/77#event-7863059642>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIEF52KB4R6PV5QDPYYCOTWJQXJRANCNFSM6AAAAAASHJGMQA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-11-23 03:14 UTC, wilsont3 requested changes
@addelian  I was able to look at this and it is great.  After looking at this, I am wondering if we want to keep first_time_homeless and date_became_homeless and reason_for_homelessness in the client details, but Megan will have to tell us about that.

One last thing that still needs to be done is filtering out clients on the location_camps screen based on the most recent dwelling type from the dwelling list.  Let me know if you can do this.  I have some time tomorrow if you don't to get this last change in there.

2022-11-23 03:14 UTC, wilsont3 commented on src/app/location-camp/location-camp.component.html
> +            <th class="text-left">Dwelling</th>
Let's have this be the second column in this grid

2022-11-23 03:14 UTC, wilsont3 commented on src/app/insert-modals/client-dwelling/client-dwelling.component.ts
> +      clientDwelling.date_became_homeless = new Date(this.date_became_homeless);
I had to add _new Date(theDate)_ here because the date was not going into the database correctly as it was coming in as dd/mm/yyyy (meaning dates like 12/30/2022 were not being entered at all).  This is a quirk of TypeScript I have found.

2022-11-23 03:57 UTC, addelian commented
@wilsont3 I'm willing to give the filtering a shot, but I'm not sure I follow what's being asked. Do we just want to ensure that the dwelling being shown on the location_camps page is the most recent dwelling? Or is there a filter you want to be applied beyond that?

2022-11-23 19:35 UTC, wilsont3 commented
So what is being asked here is that, if a volunteer is signed in as a heat
route, we filter out the clients that appear at a camp if their Dwelling
type cannot support a propane heater. Currently, this filtering is being
done on the location_camp screen.

Tim

On Tue, Nov 22, 2022, 9:57 PM Nic Addelia ***@***.***> wrote:

> @wilsont3 <https://github.com/wilsont3> I'm willing to give the filtering
> a shot, but I'm not sure I follow what's being asked. Do we just want to
> ensure that the dwelling being shown on the location_camps page is the most
> recent dwelling? Or is there a filter you want to be applied beyond that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KevinLewisIowa/JoppaTest/pull/77#issuecomment-1324517625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJIEF57JGP7CETFGZZJ3EDLWJWI23ANCNFSM6AAAAAASHJGMQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-25 23:01 UTC, addelian commented
@wilsont3 I added logic on the location-camp screen to get the most recent dwelling pulled up, and am filtering the results if it's a heat route. I know we still want to confirm the location of the fields, so I'll wait to hear back from everyone before I consider this wrapped up. Thanks!

2022-11-28 03:16 UTC, merged